### PR TITLE
attempt at making transferkudos work with discord names

### PR DESCRIPTION
**Pull request by Jayleaf**
a bit rusty with typescript, not too sure if it'll work first try lol

### CODE REVIEW

**Comment by ZeldaFan0225** [comment]
Have you even tested the additions?

**Comment by Jayleaf** [comment]
> Have you even tested the additions?

No, not yet; I'd like to because obviously it's not a great idea to test on the main version, but I'm not entirely sure how I'd be able to. I believe I'd need access to a database that has discord users on it so I can test sending to someone, as If I create my own I'd have nobody to test with. I'd love to test it properly if you can tell me how exactly I should go about it lol.

**Comment by ZeldaFan0225** [comment]
added it myself as your pr had some errors both type wise as well as format wise (command option name, ...)

**Comment by db0** [comment]
Thank you both!

**Pull request closed without merging**
